// Code generated by protoc-gen-go. DO NOT EDIT.
// source: testdata/good/good.proto

package validate_proto_http_testdata_good

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("testdata/good/good.proto", fileDescriptor_92e29827a28bdb63) }

var fileDescriptor_92e29827a28bdb63 = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x8f, 0xcf, 0x4a, 0xf3, 0x40,
	0x14, 0xc5, 0xbf, 0x7e, 0x62, 0xc1, 0x11, 0x84, 0x0e, 0x52, 0x24, 0x71, 0x61, 0xb3, 0x70, 0xd1,
	0xc5, 0x04, 0xeb, 0x2e, 0x5b, 0x29, 0xba, 0xf0, 0x1f, 0x16, 0x11, 0xdd, 0x94, 0x69, 0xe7, 0x36,
	0x19, 0x4c, 0x72, 0x87, 0xc9, 0x4d, 0x41, 0xa4, 0x1b, 0x5f, 0xc1, 0x97, 0x72, 0xef, 0x2b, 0xf8,
	0x20, 0x92, 0x19, 0x2b, 0xb8, 0x70, 0x11, 0x37, 0x03, 0x77, 0xee, 0x39, 0xbf, 0x7b, 0x0e, 0xdb,
	0x23, 0xa8, 0x48, 0x49, 0x92, 0x71, 0x8a, 0xa8, 0xdc, 0x23, 0x8c, 0x45, 0x42, 0x3e, 0x58, 0xca,
	0x5c, 0x2b, 0x49, 0x30, 0x75, 0xf3, 0x34, 0x23, 0x32, 0x62, 0xad, 0x16, 0x8d, 0x30, 0x08, 0x53,
	0xc4, 0x34, 0x87, 0xd8, 0x09, 0x66, 0xf5, 0x22, 0x86, 0xc2, 0xd0, 0x93, 0xf7, 0x07, 0xfb, 0x5f,
	0x4b, 0x69, 0x74, 0x2c, 0xcb, 0x12, 0x49, 0x92, 0xc6, 0xb2, 0xf2, 0xdb, 0xd1, 0xdb, 0x06, 0xdb,
	0x3e, 0x45, 0x54, 0x13, 0xb0, 0x4b, 0x3d, 0x07, 0x7e, 0xc9, 0xba, 0x13, 0x5d, 0x98, 0x1c, 0x78,
	0x5f, 0x78, 0xa3, 0x58, 0x53, 0xc5, 0xb8, 0xa1, 0x06, 0xbf, 0xfc, 0x47, 0xbb, 0x2f, 0xef, 0x1f,
	0xaf, 0xff, 0x77, 0xa2, 0x2d, 0xdf, 0xa0, 0xb6, 0x79, 0xd2, 0x19, 0xf2, 0x47, 0xd6, 0x6b, 0xf0,
	0xb7, 0x37, 0xe7, 0xd7, 0xd2, 0xca, 0x02, 0x08, 0x6c, 0xd5, 0x1a, 0x7d, 0xe8, 0xd0, 0x07, 0x51,
	0xe8, 0xd1, 0xcf, 0xa6, 0x41, 0x1d, 0xad, 0xdc, 0x0d, 0x3f, 0x8c, 0x56, 0xcd, 0xb1, 0x7b, 0xd6,
	0xf3, 0xe1, 0xaf, 0x28, 0x03, 0x7b, 0x01, 0x94, 0xa1, 0xfa, 0x6b, 0x0f, 0xfe, 0xb3, 0xc7, 0x98,
	0xf5, 0x3c, 0xef, 0x4e, 0x53, 0x86, 0x35, 0x9d, 0x11, 0x99, 0xd6, 0xe8, 0x7f, 0xfc, 0x81, 0x6d,
	0x9e, 0x60, 0x8e, 0x65, 0x6b, 0xeb, 0xc0, 0xa5, 0x0a, 0xa3, 0xfe, 0x77, 0xaa, 0x78, 0xa1, 0x6d,
	0x45, 0x49, 0x05, 0x73, 0x2c, 0x55, 0xd2, 0x19, 0xce, 0xba, 0xce, 0x72, 0xfc, 0x19, 0x00, 0x00,
	0xff, 0xff, 0xf0, 0x57, 0xf4, 0x09, 0x4b, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GoodServiceClient is the client API for GoodService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GoodServiceClient interface {
	Simple(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	GoodURLParameters(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	SimpleOtherMethod(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	MethodWithoutHttp(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	Colon(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
}

type goodServiceClient struct {
	cc *grpc.ClientConn
}

func NewGoodServiceClient(cc *grpc.ClientConn) GoodServiceClient {
	return &goodServiceClient{cc}
}

func (c *goodServiceClient) Simple(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/validate_proto_http.testdata.good.GoodService/Simple", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodServiceClient) GoodURLParameters(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/validate_proto_http.testdata.good.GoodService/GoodURLParameters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodServiceClient) SimpleOtherMethod(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/validate_proto_http.testdata.good.GoodService/SimpleOtherMethod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodServiceClient) MethodWithoutHttp(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/validate_proto_http.testdata.good.GoodService/MethodWithoutHttp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodServiceClient) Colon(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/validate_proto_http.testdata.good.GoodService/Colon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoodServiceServer is the server API for GoodService service.
type GoodServiceServer interface {
	Simple(context.Context, *empty.Empty) (*empty.Empty, error)
	GoodURLParameters(context.Context, *empty.Empty) (*empty.Empty, error)
	SimpleOtherMethod(context.Context, *empty.Empty) (*empty.Empty, error)
	MethodWithoutHttp(context.Context, *empty.Empty) (*empty.Empty, error)
	Colon(context.Context, *empty.Empty) (*empty.Empty, error)
}

func RegisterGoodServiceServer(s *grpc.Server, srv GoodServiceServer) {
	s.RegisterService(&_GoodService_serviceDesc, srv)
}

func _GoodService_Simple_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodServiceServer).Simple(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/validate_proto_http.testdata.good.GoodService/Simple",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodServiceServer).Simple(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodService_GoodURLParameters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodServiceServer).GoodURLParameters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/validate_proto_http.testdata.good.GoodService/GoodURLParameters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodServiceServer).GoodURLParameters(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodService_SimpleOtherMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodServiceServer).SimpleOtherMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/validate_proto_http.testdata.good.GoodService/SimpleOtherMethod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodServiceServer).SimpleOtherMethod(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodService_MethodWithoutHttp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodServiceServer).MethodWithoutHttp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/validate_proto_http.testdata.good.GoodService/MethodWithoutHttp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodServiceServer).MethodWithoutHttp(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodService_Colon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodServiceServer).Colon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/validate_proto_http.testdata.good.GoodService/Colon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodServiceServer).Colon(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _GoodService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "validate_proto_http.testdata.good.GoodService",
	HandlerType: (*GoodServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Simple",
			Handler:    _GoodService_Simple_Handler,
		},
		{
			MethodName: "GoodURLParameters",
			Handler:    _GoodService_GoodURLParameters_Handler,
		},
		{
			MethodName: "SimpleOtherMethod",
			Handler:    _GoodService_SimpleOtherMethod_Handler,
		},
		{
			MethodName: "MethodWithoutHttp",
			Handler:    _GoodService_MethodWithoutHttp_Handler,
		},
		{
			MethodName: "Colon",
			Handler:    _GoodService_Colon_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "testdata/good/good.proto",
}
